### ISSUE TITLE
GPS Not Fix Now - CME Error 52

### ISSUE THREAD

**Issue by DrGrauselGlatz** [IOT-MCU/ESP-12S-A9-A9G-GPRS-Node-v1.0#2]
I use the Board with the ESP8266 Board Version 2.5.0 as mentioned in the docs.

By using the official "Get GPS Location" I always receive the following issue in the debug window:

+LOCATION: GPS NOT FIX NOW
+CME ERROR: 52

**Comment by IOT-MCU** [comment]
Hi dear,
Thanks contact with us.
Regarding the GPS function, please note the following:
1. GPS antenna must be placed outdoors
2. Battery powered

**Comment by rcomellas** [comment]
The same problem for me. 
I'm testing outdoors and battery powered, but GPS doesn't fix and the following message appears on Serial:
+LOCATION: GPS NOT FIX NOW
+CME ERROR: 52

The GSM LED blinks, but not the GPS LED.
What is Error 52? I think it's not a standard CME code.

**Comment by PrzemyslawMotyl** [comment]
> The same problem for me.
> I'm testing outdoors and battery powered, but GPS doesn't fix and the following message appears on Serial:
> +LOCATION: GPS NOT FIX NOW
> +CME ERROR: 52
> 
> The GSM LED blinks, but not the GPS LED.
> What is Error 52? I think it's not a standard CME code.

I had similar issue when my A9G wasn't connected to **battery** but SIM card was inserted.
After connection to **battery** gps fix is fast and gprs also works fine.
Check if your battery is strong enough.
When I removed SIM card then GPS fix also worked even indoors near window.
