### ISSUE TITLE
GPS position - longitude is always 0

### ISSUE THREAD

**Issue by Gronis** [IOT-MCU/ESP-12S-A9-A9G-GPRS-Node-v1.0#4]
I get correct latitude but longitude is always 0. GPS measurements are taken outside.
```
AT+GPS=1

OK

AT+LOCATION=2

5xxx.xxxx,0

OK
```
x is a censored number.

A9/A9G
V01.06.20171130RC
Ai Thinker Co.LTD

**Comment by IOT-MCU** [comment]
Hi,
Thanks for contacting with us.
So sorry to here that, before shipping, we have test all the product, It is working fine.
Could you please test with follow AT command?
AT+GPS=1
AT+GPSRD=2    //2S OUTPUT a NEMA gps information

**Comment by Gronis** [comment]
Hi,

thanks for fast reply. It seems to get the correct information (consored here, X and Y are censored digits with correct gps location).

+GPSRD:$GNGGA,081515.000,XXXX.XXXX,N,YYYYY.YYYYY,E,2,9,0.89,11.5,M,40.1,M,,*74
$GPGSA,A,3,13,19,24,15,28,17,12,10,20,,,,1.27,0.89,0.90*0A
$BDGSA,A,3,,,,,,,,,,,,,1.27,0.89,0.90*1F
$GPGSV,4,1,13,24,54,272,30,15,50,196,29,17,39,101,33,28,38,061,35*75
$GPGSV,4,2,13,13,34,157,37,19,29,129,32,10,24,311,29,36,22,157,29*75
$GPGSV,4,3,13,20,21,276,28,12,14,220,28,01,10,034,,11,05,010,*7B
$GPGSV,4,4,13,30,02,098,*4B
$BDGSV,1,1,00*68
$GNRMC,081515.000,A,XXXX.XXXX,N,YYYYY.YYYYY,E,0.492,282.80,150420,,,D*45
$GNVTG,282.80,T,,M,0.492,N,0.912,K,D*23
$GNACC,3.7*4E

Here I get the correct info. I can use the GPS data directly. Thanks!
